name: Deploy Laravel App Tesing

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22

          script: |
            cd /var/www/testing

            echo "Pull latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Install Composer dependencies..."
            composer install --no-dev --prefer-dist --optimize-autoloader

            echo "load the nvm"
            export NVM_DIR="$HOME/.nvm"
            [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

            echo "install and use node 22 version..."
            nvm install 22
            nvm use 22

            echo "Install Node dependencies..."
            npm install

            echo "Build Vue..."
            npm run build

            echo "Run migrations..."
            php artisan migrate --force

            echo "Clear caches..."
            php artisan optimize:clear

            echo "Optimize application..."
            php artisan optimize

            echo "Restart queue..."
            php artisan queue:restart

            echo "Deployment completed!"
