name: Deploy Laravel App Tesing

on:
  push:
    branches:
      - main

  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: "22"
          cache: "npm"
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22

          script: |
            cd /var/www/testing

            echo "Pull latest code..."
            git fetch origin
            git reset --hard origin/main

            echo "Install Composer dependencies..."
            composer install --no-dev --prefer-dist --optimize-autoloader

            echo "Install Node dependencies..."
            npm install

            echo "Build Vue..."
            npm run build

            echo "Run migrations..."
            php artisan migrate --force

            echo "Clear caches..."
            php artisan optimize:clear

            echo "Optimize application..."
            php artisan optimize

            echo "Restart queue..."
            php artisan queue:restart

            echo "Deployment completed!"
